### ISSUE TITLE
How do I build it?

### ISSUE THREAD

**Issue by TruncatedDinosour** [AliChraghi/kl#1]

**Comment by AliChraghi** [comment]
build:
```sh
zig build
```
run:
```sh
zig build run -- directory/ # everything after `--` is kl argument
```
also checkout below tutorials 
- [Zig Learn](https://ziglearn.org/chapter-3/)
- [Zig News](https://zig.news/xq/zig-build-explained-part-1-59lf)

if you have any other question, join to one of the zig [communities](https://github.com/ziglang/zig/wiki/Community) ([main server](https://discord.gg/gxsFFjE) in discord is suggested)
